"""Original ambient synthesis and readable action sounds, with optional audio.

The bundled WAVs are generated by ``assets/generate_audio.py`` using only the
standard library.  Missing hardware or missing sound files never block play.
"""

from __future__ import annotations

import math
from pathlib import Path


def _bounded(value, default=0.0):
    try:
        number = float(value)
        return min(1.0, max(0.0, number)) if math.isfinite(number) else default
    except (TypeError, ValueError, OverflowError):
        return default


class AudioManager:
    """Small, cross-fading audio layer that also works with Panda's null driver."""

    EFFECTS = {
        "scan": (0.55, 0.30), "mine": (0.32, 0.11),
        "collect": (0.50, 0.10), "craft": (0.57, 0.18),
        "launch": (0.55, 0.50), "warp": (0.56, 0.70),
        "ui": (0.28, 0.05), "land": (0.42, 0.40),
        "alert": (0.43, 1.25), "discover": (0.56, 0.40),
    }

    def __init__(self, app, volume=0.45):
        self.volume = _bounded(volume, 0.45)
        self.enabled = False
        self._effects = {}
        self._loops = {}
        self._levels = {"surface": 0.0, "space": 0.0, "engine": 0.0}
        self._clock = 0.0
        self._last_played = {}
        self._destroyed = False
        self._engine_pitch = 0.85
        try:
            managers = getattr(app, "sfxManagerList", ())
            if not managers or not any(m.isValid() for m in managers):
                return
            root = Path(__file__).resolve().parent.parent / "assets" / "audio"
            for name in (*self.EFFECTS, "surface", "space", "engine"):
                path = root / (name + ".wav")
                if not path.is_file():
                    continue
                # Filename.fromOsSpecific handles Windows drive letters as well.
                from panda3d.core import Filename
                sound = app.loader.loadSfx(Filename.fromOsSpecific(str(path)))
                if sound is None:
                    continue
                if name in self.EFFECTS:
                    sound.setVolume(self.volume * self.EFFECTS[name][0])
                    self._effects[name] = sound
                else:
                    sound.setLoop(True)
                    sound.setVolume(0.0)
                    sound.play()
                    self._loops[name] = sound
            self.enabled = bool(self._effects or self._loops)
        except Exception:
            # Sound is decoration.  Devices may disappear or fail to initialize.
            self._silence()

    def play(self, name):
        if not self.enabled or self._destroyed or name not in self._effects:
            return
        gain, cooldown = self.EFFECTS[name]
        if self._clock - self._last_played.get(name, -1000.0) < cooldown:
            return
        self._last_played[name] = self._clock
        try:
            sound = self._effects[name]
            sound.setVolume(self.volume * gain)
            sound.play()
        except Exception:
            self._silence()

    def update(self, dt, mode, thrust=0):
        if self._destroyed:
            return
        try:
            dt = float(dt)
            dt = min(0.25, max(0.0, dt)) if math.isfinite(dt) else 0.0
        except (TypeError, ValueError, OverflowError):
            dt = 0.0
        self._clock += dt
        if not self.enabled:
            return
        thrust = _bounded(abs(thrust) if isinstance(thrust, (int, float)) else 0)
        flying = mode in ("flight", "orbit")
        targets = {
            "surface": 0.31 if mode in ("surface", "flight") else 0.0,
            "space": 0.40 if mode == "orbit" else (0.17 if mode == "title" else 0.0),
            "engine": (0.10 + 0.40 * thrust) if flying else 0.0,
        }
        fade = 1.0 - math.exp(-dt * 1.5)
        try:
            for name, sound in self._loops.items():
                self._levels[name] += (targets[name] - self._levels[name]) * fade
                sound.setVolume(self._levels[name] * self.volume)
            engine = self._loops.get("engine")
            if engine is not None:
                self._engine_pitch += (0.85 + thrust * 0.6 - self._engine_pitch) * fade
                engine.setPlayRate(self._engine_pitch)
        except Exception:
            self._silence()

    def set_volume(self, value):
        self.volume = _bounded(value, self.volume)
        try:
            for name, sound in self._effects.items():
                sound.setVolume(self.volume * self.EFFECTS[name][0])
            for name, sound in self._loops.items():
                sound.setVolume(self.volume * self._levels[name])
        except Exception:
            self._silence()

    def _silence(self):
        for sound in (*self._effects.values(), *self._loops.values()):
            try:
                sound.stop()
            except Exception:
                pass
        self.enabled = False

    def destroy(self):
        self._silence()
        self._effects.clear()
        self._loops.clear()
        self._destroyed = True
