"""Original ambient synthesis and readable action sounds, with optional audio.

The bundled WAVs are generated by ``assets/generate_audio.py`` using only the
standard library.  Missing hardware or missing sound files never block play.
"""

from __future__ import annotations

import math
from pathlib import Path

try:
    from panda3d.core import Filename
except ImportError:  # pragma: no cover - Panda3D is always present in-game
    Filename = None


def _bounded(value, default=0.0):
    try:
        number = float(value)
        return min(1.0, max(0.0, number)) if math.isfinite(number) else default
    except (TypeError, ValueError, OverflowError):
        return default


class AudioManager:
    """Small, cross-fading audio layer that also works with Panda's null driver."""

    EFFECTS = {
        "scan": (0.55, 0.30), "mine": (0.32, 0.11),
        "collect": (0.50, 0.10), "craft": (0.57, 0.18),
        "launch": (0.55, 0.50), "warp": (0.56, 0.70),
        "ui": (0.28, 0.05), "land": (0.42, 0.40),
        "alert": (0.43, 1.25), "discover": (0.56, 0.40),
    }

    def __init__(self, app, volume=0.45):
        self.volume = _bounded(volume, 0.45)
        self.enabled = False
        self._effects = {}
        self._loops = {}
        self._levels = {"surface": 0.0, "space": 0.0, "engine": 0.0}
        # Last per-loop volume (and engine pitch) pushed to the driver. At
        # steady state update() skips redundant driver calls entirely.
        self._applied = {}
        self._pitch_applied = None
        self._clock = 0.0
        self._last_played = {}
        self._destroyed = False
        self._engine_pitch = 0.85
        self._failures = 0
        if self.volume <= 0 or getattr(app, "no_audio", False):
            return
        try:
            managers = getattr(app, "sfxManagerList", ())
            if not managers or not any(m.isValid() for m in managers):
                return
            root = Path(__file__).resolve().parent.parent / "assets" / "audio"
            for name in (*self.EFFECTS, "surface", "space", "engine"):
                try:
                    path = root / (name + ".wav")
                    if not path.is_file():
                        continue
                    if Filename is None:
                        continue
                    # Filename.fromOsSpecific handles Windows drive letters as well.
                    sound = app.loader.loadSfx(Filename.fromOsSpecific(str(path)))
                    if sound is None:
                        continue
                    if name in self.EFFECTS:
                        sound.setVolume(self.volume * self.EFFECTS[name][0])
                        self._effects[name] = sound
                    else:
                        sound.setLoop(True)
                        sound.setVolume(0.0)
                        sound.play()
                        self._loops[name] = sound
                except Exception:
                    self._failures += 1
                    continue
            self.enabled = bool(self._effects or self._loops)
        except Exception:
            # Sound is decoration.  Devices may disappear or fail to initialize.
            self._failures += 1
            if self._failures > 3:
                self._silence()

    def play(self, name):
        if not self.enabled or self._destroyed or name not in self._effects:
            return
        gain, cooldown = self.EFFECTS[name]
        if self._clock - self._last_played.get(name, -1000.0) < cooldown:
            return
        self._last_played[name] = self._clock
        try:
            sound = self._effects[name]
            sound.setVolume(self.volume * gain)
            sound.play()
        except Exception:
            self._failures += 1
            try:
                self._effects.pop(name, None)
            except Exception:
                pass
            if self._failures > 3:
                self._silence()

    def update(self, dt, mode, thrust=0):
        if self._destroyed:
            return
        try:
            dt = float(dt)
            dt = min(0.25, max(0.0, dt)) if math.isfinite(dt) else 0.0
        except (TypeError, ValueError, OverflowError):
            dt = 0.0
        self._clock += dt
        if not self.enabled or not self._loops:
            return
        thrust = _bounded(abs(thrust) if isinstance(thrust, (int, float)) else 0)
        flying = mode == "flight" or mode == "orbit"
        surface_t = 0.31 if mode == "surface" or mode == "flight" else 0.0
        if mode == "orbit":
            space_t = 0.40
        elif mode == "title":
            space_t = 0.17
        else:
            space_t = 0.0
        engine_t = (0.10 + 0.40 * thrust) if flying else 0.0
        fade = 1.0 - math.exp(-dt * 1.5)
        if fade <= 0.0:
            return
        levels = self._levels
        applied = self._applied
        volume = self.volume
        dead = None
        try:
            for name, sound in self._loops.items():
                if name == "surface":
                    target = surface_t
                elif name == "space":
                    target = space_t
                elif name == "engine":
                    target = engine_t
                else:
                    target = levels.get(name, 0.0)
                level = levels.get(name, 0.0)
                step = (target - level) * fade
                if step:
                    # Snap inaudible tails so the level converges in finite
                    # steps instead of easing toward the target forever.
                    level = target if abs(target - level) < 5e-4 else level + step
                    levels[name] = level
                gain = level * volume
                if applied.get(name) != gain:
                    try:
                        sound.setVolume(gain)
                    except Exception:
                        if dead is None:
                            dead = []
                        dead.append(name)
                        continue
                    applied[name] = gain
            if dead is not None:
                for name in dead:
                    sound = self._loops.pop(name, None)
                    applied.pop(name, None)
                    self._failures += 1
                    try:
                        sound.stop()
                    except Exception:
                        pass
            engine = self._loops.get("engine")
            if engine is not None:
                pitch = self._engine_pitch + (0.85 + thrust * 0.6 - self._engine_pitch) * fade
                if abs(pitch - self._engine_pitch) < 1e-4:
                    pitch = 0.85 + thrust * 0.6
                self._engine_pitch = pitch
                if self._pitch_applied != pitch:
                    engine.setPlayRate(pitch)
                    self._pitch_applied = pitch
        except Exception:
            self._failures += 1
            if self._failures > 3:
                self._silence()
    def set_volume(self, value):
        self.volume = _bounded(value, self.volume)
        if self.volume <= 0:
            self._silence()
            return
        try:
            for name, sound in self._effects.items():
                sound.setVolume(self.volume * self.EFFECTS[name][0])
            for name, sound in self._loops.items():
                gain = self.volume * self._levels[name]
                sound.setVolume(gain)
                self._applied[name] = gain
            if (not self.enabled and not self._destroyed and self._failures <= 3
                    and (self._effects or self._loops)):
                # Muting stops the loop sounds; raising the volume again must
                # restart them, otherwise the game stays silent until reload.
                for sound in self._loops.values():
                    try:
                        sound.play()
                    except Exception:
                        self._failures += 1
                self.enabled = True
        except Exception:
            self._failures += 1
            if self._failures > 3:
                self._silence()


    def _silence(self):
        for sound in (*self._effects.values(), *self._loops.values()):
            try:
                sound.stop()
            except Exception:
                pass
        self.enabled = False

    def destroy(self):
        self._silence()
        self._effects.clear()
        self._loops.clear()
        self._destroyed = True
